/*
 * This file was generated with makeClass. Edit only those parts of the code inside
 * of 'EXISTING_CODE' tags.
 */
import { getFieldValue } from './Appearances';

//----------------------------------------------------------------------------
// auto-generate: schema
export const appearancesSchema = [
  {
    name: 'ID',
    selector: 'id',
    type: 'string',
    hidden: true,
    searchable: true,
    onDisplay: getFieldValue,
  },
  {
    name: 'Date/Block',
    selector: 'date',
    type: 'string',
    width: 2,
    chart: 'range',
    underField: 'marker',
    onDisplay: getFieldValue,
  },
  {
    name: 'Marker',
    selector: 'marker',
    type: 'string',
    hidden: true,
    width: 2,
    detail: true,
    onDisplay: getFieldValue,
  },
  {
    name: 'From',
    selector: 'from',
    type: 'address',
    width: 5,
    chart: 'range',
    searchable: true,
    underField: 'fromName',
    onDisplay: getFieldValue,
  },
  {
    name: 'fromName',
    selector: 'fromName',
    type: 'string',
    hidden: true,
    searchable: true,
    onDisplay: getFieldValue,
  },
  {
    name: 'To',
    selector: 'to',
    type: 'address',
    width: 5,
    chart: 'range',
    searchable: true,
    underField: 'toName',
    onDisplay: getFieldValue,
  },
  {
    name: 'toName',
    selector: 'toName',
    type: 'string',
    hidden: true,
    searchable: true,
    onDisplay: getFieldValue,
  },
  {
    name: 'Value',
    selector: 'value',
    type: 'wei',
    hidden: true,
    chart: 'domain',
  },
  {
    name: 'Ether',
    selector: 'ether',
    type: 'blknum',
    hidden: true,
    width: 2,
    chart: 'domain',
  },
  {
    name: 'Sep1',
    selector: 'separator1',
    type: 'separator',
    hidden: true,
    detail: true,
  },
  {
    name: 'Asset',
    selector: 'statements.asset',
    type: 'string',
    width: 1,
    align: 'center',
    detail: true,
    onDisplay: getFieldValue,
  },
  {
    name: 'Beg',
    selector: 'statements.begBal',
    type: 'value',
    width: 2,
    detail: true,
    onDisplay: getFieldValue,
  },
  {
    name: 'Beg Diff',
    selector: 'statements.begBalDiff',
    type: 'value',
    hidden: true,
    width: 2,
    onDisplay: getFieldValue,
  },
  {
    name: 'Total In',
    selector: 'statements.totalin',
    type: 'value',
    width: 2,
    detail: true,
    onDisplay: getFieldValue,
  },
  {
    name: 'Income',
    selector: 'statements.inflow',
    type: 'value',
    hidden: true,
    width: 2,
    onDisplay: getFieldValue,
  },
  {
    name: 'I-Income',
    selector: 'statements.intInflow',
    type: 'value',
    hidden: true,
    width: 2,
    onDisplay: getFieldValue,
  },
  {
    name: 'S-Income',
    selector: 'statements.suicideInflow',
    type: 'value',
    hidden: true,
    width: 2,
    onDisplay: getFieldValue,
  },
  {
    name: 'Total Out',
    selector: 'statements.totalout',
    type: 'value',
    width: 2,
    detail: true,
    onDisplay: getFieldValue,
  },
  {
    name: 'Spending',
    selector: 'statements.outflow',
    type: 'value',
    hidden: true,
    width: 2,
    onDisplay: getFieldValue,
  },
  {
    name: 'I-Spending',
    selector: 'statements.intOutflow',
    type: 'value',
    hidden: true,
    width: 2,
    onDisplay: getFieldValue,
  },
  {
    name: 'S-Spending',
    selector: 'statements.suicideOutflow',
    type: 'value',
    hidden: true,
    width: 2,
    onDisplay: getFieldValue,
  },
  {
    name: 'Gas Cost',
    selector: 'statements.weiGasCost',
    type: 'value',
    hidden: true,
    width: 2,
    chart: 'domain',
    onDisplay: getFieldValue,
  },
  {
    name: 'Ending',
    selector: 'statements.endBal',
    type: 'value',
    width: 2,
    chart: 'domain',
    detail: true,
    onDisplay: getFieldValue,
  },
  {
    name: 'Calc',
    selector: 'statements.endBalCalc',
    type: 'value',
    hidden: true,
    width: 2,
    onDisplay: getFieldValue,
  },
  {
    name: 'End Diff',
    selector: 'statements.endBalDiff',
    type: 'value',
    hidden: true,
    width: 2,
    onDisplay: getFieldValue,
  },
  {
    name: 'Type',
    selector: 'statements.reconciliationType',
    type: 'string',
    width: 2,
    onDisplay: getFieldValue,
  },
  {
    name: 'Okay',
    selector: 'statements.reconciled',
    type: 'string',
    align: 'center',
    detail: true,
    onDisplay: getFieldValue,
  },
  {
    name: 'Gas',
    selector: 'gas',
    type: 'gas',
    hidden: true,
    width: 2,
  },
  {
    name: 'Gas Used',
    selector: 'gasUsed',
    type: 'gas',
    hidden: true,
    width: 2,
    chart: 'domain',
  },
  {
    name: 'Gas Price',
    selector: 'gasPrice',
    type: 'wei',
    hidden: true,
    width: 2,
  },
  {
    name: 'Gas Cost (Eth)',
    selector: 'etherGasCost',
    type: 'ether',
    hidden: true,
    width: 2,
  },
  {
    name: 'Sep2',
    selector: 'separator2',
    type: 'separator',
    hidden: true,
    detail: true,
  },
  {
    name: 'Compressed Tx',
    selector: 'compressedTx',
    type: 'string',
    hidden: true,
    detail: true,
    onDisplay: getFieldValue,
  },
  {
    name: 'Compressed Logs',
    selector: 'compressedLog',
    type: 'string',
    hidden: true,
    detail: true,
    onDisplay: getFieldValue,
  },
  {
    name: 'Creations',
    selector: 'creations',
    type: 'string',
    hidden: true,
    detail: true,
    onDisplay: getFieldValue,
  },
  {
    name: 'Sep3',
    selector: 'separator3',
    type: 'separator',
    hidden: true,
  },
  {
    name: 'Age',
    selector: 'age',
    type: 'blknum',
    hidden: true,
  },
  {
    name: 'Encoding',
    selector: 'encoding',
    type: 'hash',
    hidden: true,
  },
  {
    name: 'Receipt',
    selector: 'receipt',
    type: 'CReceipt',
    hidden: true,
  },
  {
    name: 'Articulated Tx',
    selector: 'articulatedTx',
    type: 'CFunction',
    hidden: true,
    searchable: true,
  },
  {
    name: 'Traces',
    selector: 'traces',
    type: 'CTraceArray',
    hidden: true,
  },
  {
    name: 'Block Hash',
    selector: 'blockHash',
    type: 'hash',
    hidden: true,
  },
  {
    name: 'Blk',
    selector: 'blockNumber',
    type: 'blknum',
    hidden: true,
    width: 1,
  },
  {
    name: 'Tx',
    selector: 'transactionIndex',
    type: 'string',
    hidden: true,
    width: 1,
  },
  {
    name: 'Timestamp',
    selector: 'timestamp',
    type: 'timestamp',
    hidden: true,
    chart: 'range',
  },
  {
    name: 'Hash',
    selector: 'hash',
    type: 'hash',
    hidden: true,
    width: 5,
    searchable: true,
  },
  {
    name: 'Nonce',
    selector: 'nonce',
    type: 'blknum',
    hidden: true,
  },
  {
    name: 'Input',
    selector: 'input',
    type: 'string',
    hidden: true,
  },
  {
    name: 'Finalized',
    selector: 'finalized',
    type: 'bool',
    hidden: true,
  },
  {
    name: 'Function',
    selector: 'function',
    type: 'string',
    hidden: true,
    width: 5,
    searchable: true,
    onDisplay: getFieldValue,
  },
  {
    name: 'Events',
    selector: 'events',
    type: 'string',
    hidden: true,
    width: 3,
  },
  {
    name: 'Price',
    selector: 'price',
    type: 'double',
    hidden: true,
    width: 3,
  },
  {
    name: 'Date Short',
    selector: 'datesh',
    type: 'string',
    hidden: true,
  },
  {
    name: 'Time',
    selector: 'time',
    type: 'string',
    hidden: true,
  },
  {
    name: 'Error',
    selector: 'isError',
    type: 'string',
    hidden: true,
    width: 1,
    isPill: true,
  },
  {
    name: 'Internal',
    selector: 'internal',
    type: 'string',
    hidden: true,
    width: 2,
    align: 'center',
    onDisplay: getFieldValue,
  },
  {
    name: 'Icons',
    selector: 'icons',
    type: 'icons',
    hidden: true,
  },
];
// auto-generate: schema
