[settings]
# pages are the top level menu choices only. Not to be confused with the generated code from_source
pages = "\
    dashboard|separator|\
    collections|monitors|accounts|tags|explorer|separator|\
    names|signatures|digests|caches|other|separator|\
    settings|support"

schemas = "\
    dashboard|collections|monitors|accounts|tags|\
    names|signatures|digests|\
    caches|other|settings|settings-schemas|settings-systems|support|\
    explorer|\
    explorer-blocks|explorer-transactions|explorer-receipts|explorer-logs|\
    explorer-traces|explorer-traceActions|explorer-traceResults|\
    explorer-functions|explorer-parameters|explorer-abis|\
    explorer-pricequotes|explorer-pricesources"

from_source = "\
    collections|monitors|accounts|tags|\
    explorer-blocks|explorer-transactions|explorer-receipts|explorer-logs|explorer-traces|\
    names|signatures|caches|other"
