[settings]
class = "CAppearances"
noPage = true
recordIcons = "viewing,exporting,importing"
defaultSort = "tags,address"
dataUrl = "http://localhost:8080/export"
dataQuery = "addrs=record.address&verbose=10&dollars"
cmdUrl = ""

[[subpages]]
list = [
    { page = "appearances", subpage = "" },
]
