[settings]
class = "CAppearances"
noPage = true
recordIcons = "viewing,exporting,importing"
defaultSort = "blockNumber,transactionIndex"
defaultTags = "['Tokens', 'Grants', 'Airdrops', '|', 'Neighbors', 'Balances', 'Functions', 'Events', 'Creations', 'SelfDestructs']"

dataUrl = "http://localhost:8080/export"
dataQuery = "addrs=' + addresses.value + '&verbose=7&dollars&articulate&write_txs&write_traces"
cmdUrl = "none"

[[subpages]]
list = [
    { page = "appearances", subpage = "" },
]
