[settings]
class = "CExplorer"
url = "http://localhost:8080/[{LONG}]"
query_blocks = "blocks=' + current + '&hashes_only&verbose=10"
query_transactions = "transactions=' + current + '&verbose=10&force"
query_receipts = "transactions=' + current + '&verbose=10"
query_logs = "transactions=' + current + '&verbose=10"
query_traces = "transactions=' + current + '&verbose=10"


[[subpages]]
list = [
    { page = "explorer", subpage = "", route = "" },
    { page = "explorer", subpage = "Blocks", options = "blocks_EQ_latest&hashes_only" },
    { page = "explorer", subpage = "Transactions", options = "transactions_EQ_8001001.0" },
    { page = "explorer", subpage = "Receipts", options = "transactions_EQ_8001001.0" },
    { page = "explorer", subpage = "Logs", options = "transactions_EQ_46147.0" },
    { page = "explorer", subpage = "Traces", options = "transactions_EQ_8001001.1" },
]
