[settings]
class = "CMonitors"
recordIcons = "viewing,editing,view,exporting,importing"
defaultSort = "tags,address"
defaultSearch = "tags,address,name"
dataUrl = "http://localhost:8080/status"
dataQuery = "modes=monitors&details&verbose=10"
cmdUrl = "http://localhost:8080/rm"

[[subpages]]
list = [
    { page = "monitors", subpage = "" },
    { page = "monitors", subpage = "Active", route = "active", options = "" },
    { page = "monitors", subpage = "Paused", route = "paused", options = "" },
    { page = "monitors", subpage = "Pending", route = "pending", options = "" },
    { page = "support", subpage = "Separator" },
    { page = "monitors", subpage = "Explore", route = "explore", options = "", component = "<Appearances />" },
]
