[settings]
class = "CMonitors"
recordIcons = "viewing,editing,exploring,exporting,importing"
defaultSort = "tags,address"
url = "http://localhost:8080/status"
query = "modes=monitors&details&verbose=10"

[[subpages]]
list = [
    { page = "monitors", subpage = "" },
    { page = "monitors", subpage = "Your Monitors", route = "yours", options = "" },
    { page = "monitors", subpage = "Shared Monitors", route = "shared", options = "" },
]
