[settings]
class = "CMonitors"
recordIcons = "header-Add,Edit/Remove,Delete/Undelete,Explorer,ExternalLink,footer-CSV,footer-TXT,footer-Import"
defaultSort = "tags,address"
url = "http://localhost:8080/status"
query = "modes=monitors&details&verbose=10"

[[subpages]]
list = [
    { page = "monitors", subpage = "" },
    { page = "monitors", subpage = "Your Monitors", route = "yours", options = "" },
    { page = "monitors", subpage = "Shared Monitors", route = "shared", options = "" },
]
