[settings]
class = "CNames"
recordIcons = "header-Add,Edit/Remove,Delete/Undelete,Explorer,ExternalLink,footer-CSV,footer-TXT,footer-Import"
defaultSort = "tags,address,name"
url = "http://localhost:8080/names"
query = "verbose=10&all"

[[subpages]]
list = [
    { page = "names", subpage = "" },
]
