[settings]
class = "CNames"
recordIcons = "viewing,editing,exploring,exporting,importing"
defaultSort = "tags,address,name"
dataUrl = "http://localhost:8080/names"
dataQuery = "verbose=10&all&expand"
# cmdUrl = "http://localhost:8080/names"

[[subpages]]
list = [
    { page = "names", subpage = "" },
]
