[settings]
class = "COther"
recordIcons = "header-Add,Edit/Remove,Delete/Undelete"
defaultSort = "blockNumber,name,date"
url = "http://localhost:8080/when"
query = "verbose=10&list"

[[subpages]]
list = [
    { page = "other", subpage = "", },
    { page = "other", subpage = "Your Blocks", route = "yours", },
    { page = "other", subpage = "Known Blocks", route = "known", },
    { page = "other", subpage = "Dated Blocks", route = "dated", },
]
