[settings]
class = "COther"
recordIcons = "editing"
defaultSort = "blockNumber,name,date"
cmdUrl = "http://localhost:8080/when"
dataUrl = "http://localhost:8080/when"
dataQuery = "list"
defaultTags = "['Yours', 'Known', 'Dated']"
imports = "||getServerData, sendServerCommand, sortArray, handleClick, navigate, replaceRecord, stateFromStorage|||"

[[subpages]]
list = [
    { page = "other", subpage = "", },
]
