[settings]
class = "COther"
recordIcons = "editing"
defaultSort = "blockNumber,name,date"
dataUrl = "http://localhost:8080/when"
dataQuery = "verbose=10&list"
defaultTags = "['Yours', 'Known', 'Dated']"

[[subpages]]
list = [
    { page = "other", subpage = "", },
]
