[settings]
class = "CSignatures"
recordIcons = "header-Add,Edit/Remove,Delete/Undelete,footer-CSV,footer-TXT"
defaultSort = "encoding,type,name"
url = "http://localhost:8080/abi"
query = "verbose=10&monitored&known"

[[subpages]]
list = [
    { page = "signatures", subpage = "" },
    { page = "signatures", subpage = "Known" },
    { page = "signatures", subpage = "Monitored" },
    { page = "signatures", subpage = "Separator" },
    { page = "signatures", subpage = "Names" },
    { page = "signatures", subpage = "Params" },
    { page = "signatures", subpage = "Cross" },
]
