[settings]
class = "CTags"
recordIcons = "editing"
defaultSort = "tags,subtags1,subtags2"
cmdUrl = "http://localhost:8080/names"
dataUrl = "http://localhost:8080/names"
dataQuery = "tags"
imports = "||getServerData, sendServerCommand, sortArray, sortStrings, handleClick, replaceRecord|||"

[[subpages]]
list = [
    { page = "tags", subpage = "" },
]
