[settings]
class = "CTags"
recordIcons = "header-Add,Edit/Remove,Delete/Undelete"
defaultSort = "tags,subtags1,subtags2"
url = "http://localhost:8080/names"
query = "verbose=10&tags"

[[subpages]]
list = [
    { page = "tags", subpage = "" },
]
