[settings]
class = "CCaches"
dest_folder = "./src/pages/"

[[subpages]]
list = [
    { page = "caches", subpage = "" },
    { page = "caches", subpage = "blocks" },
    { page = "caches", subpage = "transactions" },
    { page = "caches", subpage = "traces" },
    { page = "caches", subpage = "slurps" },
    { page = "caches", subpage = "prices" },
    { page = "caches", subpage = "abis" },
]

