[settings]
class = "CDigests"
dest_folder = "./src/pages/"

[[subpages]]
list = [
    { page = "digests", subpage = "" },
    { page = "digests", subpage = "finalized" },
    { page = "digests", subpage = "staged" },
    { page = "digests", subpage = "unripe" },
    { page = "digests", subpage = "columns" },
]
