[settings]
class = "CExplorer"
dest_folder = "./src/pages/"

[[subpages]]
list = [
    { page = "explorer", subpage = "", route = "" },
    { page = "explorer", subpage = "Blocks", options = "blocks_EQ_latest&hashes_only" },
    { page = "explorer", subpage = "Transactions", options = "transactions_EQ_8001001.0" },
    { page = "explorer", subpage = "Receipts", options = "transactions_EQ_8001001.0" },
    { page = "explorer", subpage = "Logs", options = "transactions_EQ_46147.0" },
    { page = "explorer", subpage = "Traces", options = "transactions_EQ_8001001.1" },
]
