[settings]
class = "CMonitors"
dest_folder = "./src/pages/"

[[subpages]]
list = [
    { page = "monitors", subpage = "" },
    { page = "monitors", subpage = "yours", route = "/yours", options = "" },
    { page = "monitors", subpage = "shared", route = "/shared", options = "" },
]
