[settings]
class = "CMonitors"

[[subpages]]
list = [
    { page = "monitors", subpage = "" },
    { page = "monitors", subpage = "Your Monitors", route = "yours", options = "" },
    { page = "monitors", subpage = "Shared Monitors", route = "shared", options = "" },
]
