[settings]
class = "COther"
dest_folder = "./src/pages/"

[[subpages]]
list = [
    { page = "other", subpage = "", },
    { page = "other", subpage = "downloaded", },
    { page = "other", subpage = "common", },
    { page = "other", subpage = "your%20blocks", },
    { page = "other", subpage = "known%20blocks", },
    { page = "other", subpage = "dated%20blocks", },
]
