[settings]
class = "CProjects"
dest_folder = "./src/pages/"

[[subpages]]
list = [
    { page = "projects", subpage = "" },
    { page = "projects", subpage = "View...", route = "view" },
    { page = "projects", subpage = "Edit...", route = "edit" },
    { page = "projects", subpage = "Save" },
    { page = "projects", subpage = "Export" },
]
