[settings]
class = "CProjects"
dest_folder = "./src/pages/"

[[subpages]]
list = [
    { page = "projects", subpage = "" },
    { page = "projects", subpage = "view" },
    { page = "projects", subpage = "edit" },
    { page = "projects", subpage = "save" },
    { page = "projects", subpage = "export" },
]
