[settings]
class = "CSettings"
dest_folder = "./src/pages/"

[[subpages]]
list = [
    { page = "settings", subpage = "" },
    { page = "settings", subpage = "api" },
    { page = "settings", subpage = "node" },
    { page = "settings", subpage = "scraper" },
    { page = "settings", subpage = "sharing" },
    { page = "settings", subpage = "skins" },
    { page = "settings", subpage = "schemas" },
]
