[settings]
class = "CSignatures"

[[subpages]]
list = [
    { page = "signatures", subpage = "" },
    { page = "signatures", subpage = "Known" },
    { page = "signatures", subpage = "Monitored" },
    { page = "signatures", subpage = "Separator" },
    { page = "signatures", subpage = "Names" },
    { page = "signatures", subpage = "Params" },
    { page = "signatures", subpage = "Cross" },
]
