[settings]
class = "CSignatures"
dest_folder = "./src/pages/"

[[subpages]]
list = [
    { page = "signatures", subpage = "" },
    { page = "signatures", subpage = "known" },
    { page = "signatures", subpage = "monitored" },
    { page = "signatures", subpage = "names" },
    { page = "signatures", subpage = "params" },
    { page = "signatures", subpage = "cross" },
]
