[settings]
class = "CSupport"
dest_folder = "./src/pages/"

[[subpages]]
list = [
    { page = "support", subpage = "" },
    { page = "support", subpage = "keys" },
    { page = "support", subpage = "contact" },
    { page = "support", subpage = "documentation" },
    { page = "support", subpage = "licensing" },
    { page = "support", subpage = "about" },
]
